### ISSUE TITLE
文档补充

### ISSUE THREAD

**Issue by Ericj100** [dianping/zebra#2]
hello
    有没有架构图和压测结果文档？
    SQL解析请问下是用druid开源的，还是自己实现的？
    另能否有个QQ等交流工具，方便交流 :)

**Comment by ainilife** [comment]
文档我们正在补充过程中。你留一个微信联系方式吧。我加你

**Comment by Ericj100** [comment]
微信号：jun_ge1

**Comment by ainilife** [comment]
已加
