### ISSUE TITLE
动态表

### ISSUE THREAD

**Issue by Ericj100** [dianping/zebra#3]
请问下我有一个date_time时间字段：begin_time，我想已begin_time为纬度，进行分表，表我会提前生成，每天一个表：table_yyyyMMdd，这种方式支持吗？

**Comment by ainilife** [comment]
规则都是用groovy脚本，所以可以支持你的这种要求。但是用时间来做分表建有一个问题，就是你只能做=操作哦，但是我的理解你应该是需要>=,<=等操作吧。

**Comment by Ericj100** [comment]
做in操作也可以，in操作支持吗？

**Comment by ainilife** [comment]
必须支持的~~
