### ISSUE TITLE
router-rule配置里的isMaster是什么意思？

### ISSUE THREAD

**Issue by developer1981** [dianping/zebra#5]
router-rule配置里的isMaster是什么意思？ 文档上没找到

**Comment by ainilife** [comment]
哦，这个表明是否是主维度，也就说说一个分表可以有多个维度，但只有主维度支持写，其他辅助维度只能进行读。点评内部是通过binlog的方式进行复制的方式，将主维度的数据自动的复制到辅助维度上去。

**Comment by developer1981** [comment]
明白了，谢谢。 
还有问题请教，分库分表中间件有限zebra的lib方式集成到项目中的，也有server方式独立运行的，比如mycat.  这两种方式怎么选择？ zebra性能怎么样？
